### ISSUE TITLE
Where is mux-react-native-video-sdk

### ISSUE THREAD

**Issue by strathausen** [muxinc/mux-stats-sdk-react-native-video#24]
In the example in the readme, `mux-react-native-video-sdk` is used. However, I can't find it on npm. Am I missing something?

Thanks a lot for any help.

**Comment by dylanjha** [comment]
Hi @strathausen right now it can be installed via Github: https://github.com/muxinc/mux-stats-sdk-react-native-video#installation

We're working on getting it out of beta and up on npm.

Thanks, let me know if that helps! 🙌🏼

**Comment by strathausen** [comment]
Ah, did I not see this 🤦 thanks!

**Comment by dylanjha** [comment]
Interesting, can you help me understand:

[`react-native-video`](https://www.npmjs.com/package/react-native-video) works with this mux sdk
[`@tinyhood/react-native-mux-video`](https://www.npmjs.com/package/@tinyhood/react-native-mux-video) works with this mux sdk

What is the video SDK you were trying to use that was failing because of React 17?

**Comment by strathausen** [comment]
This failed for me:

`npm install "https://github.com/muxinc/mux-stats-sdk-react-native-video#v0.1.0" --save`

However, since there's AFAIK not much of a difference between React 16 and 17, I just used `--force` when installing and things seem to work fine.

**Comment by strathausen** [comment]
So I've been playing around with mux-stats-sdk-react-native-video it on React 17 and it's fine!

**Comment by dylanjha** [comment]
ohhh npm 6 used to log a warning for unmet peerDependencies but npm 7 I think fails the install now. We'll have to update that `peerDependency` for react

**Comment by jasonbodily** [comment]
Any concerns with upping the version in the package.json & README? I'd love to not have to force our build! I'd submit a PR if I could :)
