### ISSUE TITLE
Use with RN 0.64 

### ISSUE THREAD

**Issue by Kylar13** [muxinc/mux-stats-sdk-react-native-video#25]
Hello!

As you probably know, ReactNative released 0.64 around 4 months ago, and in that release bumped React's version to 17.0.1.

Because of that, I am running into this error that I don't know how to solve:
```npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myApp@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9" from mux-react-native-video-sdk@0.1.0
npm ERR! node_modules/mux-react-native-video-sdk
npm ERR!   mux-react-native-video-sdk@"https://github.com/muxinc/mux-stats-sdk-react-native-video#v0.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.```

**Comment by dylanjha** [comment]
@Kylar13 if you're using npm 6 the `npm install` should work fine (peer dependencies do not cause install errors)

Looks like you're on npm 7 where peer dependencies cause install errors, so you can get around this with `npm install --legacy-peer-deps`

Let me know if that helps. We'll have to update the peer dependency on our side in the next release.

**Comment by Kylar13** [comment]
I did get it to work with legacy deps, just FYI. Having another issue now but will post it sepparate from this
